services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Act1234@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app_network
    restart: always

  api:
    image: ${DOCKER_REGISTRY-}api
    healthcheck:
        interval: 10s
        timeout: 10s
        retries: 3
    build:
      context: .
      dockerfile: ActEmployeeManagementApi/Dockerfile
    container_name: api
    depends_on:
      - sqlserver
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Development
    #   - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ActDataBase;User Id=sa;Password=Act1234@;
    #   - ConnectionStrings__DefaultConnectionInitial=Server=sqlserver,1433;Database=master;User Id=sa;Password=Act1234@;
    # ports:
    #   - "5000:80"
    #   - "5001:443"
    networks:
      - app_network
    restart: always

networks:
  app_network:































